api_platform:
    use_symfony_listeners: true
    serializer:
        hydra_prefix: false
    inflector: api_platform.metadata.inflector
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        normalization_context:
            skip_null_values: true
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    validator:
        query_parameter_validation: true
        serialize_payload_fields: []  # Empty array means no specific fields are serialized
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        swagger_ui_extra_configuration:
            graphqlEnabled: false
    show_webby: false
    graphql:
        enabled: false
    formats:
        json:
            mime_types: ['application/json']
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
