version: '3.8'

services:
  php:
    build: .
    container_name: symfony_app
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DATABASE_URL: mysql://root:root@db:3306/library?serverVersion=8.0

  db:
    image: mysql:8
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library
    ports:
      - "3306:3306"

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - .:/var/www/html
      - ./nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - php
